export default {
  // Auth
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',

  REGISTER_SIM: 'REGISTER_SIM',
  ELIGIBILITY_INFO: 'ELIGIBILITY_INFO',

  FP_VERIFY: 'FP_VERIFY',
  CONTACT_DETAILS: 'CONTACT_DETAILS',
  SPOUSE_DETAILS: 'SPOUSE_DETAILS',
  DOCUMENTS: 'DOCUMENTS',
  CITIZEN_SHIP: 'CITIZEN_SHIP',
};
