//Constants App
export const ENR_DATA = '[FP] ENR_DATA';
export const META_DATA = '[META] META_DATA';
export const SEARCH_RESIDENT_DATA = '[SEARCH] SEARCH_RESIDENT_DATA';
export const SEARCH_CONTACT_DATA = '[SEARCH] SEARCH_CONTACT_DATA';
export const SEARCH_SPOUSE_DATA = '[SEARCH] SEARCH_SPOUSE_DATA';
export const SEARCH_DOCUMENTS_DATA = '[SEARCH] SEARCH_DOCUMENTS_DATA';
export const SEARCH_CITIZENSHIP_DATA = '[SEARCH] SEARCH_CITIZENSHIP_DATA';
